version: 0.2
  
phases:
  install:
    commands:
      - echo $toolingBucket
      - cd hello-world
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      - npm run test
      - cd ..
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam build
      # samconfig.tomlの「resolve_s3」の値を「false」に変更
      - sam package --s3-bucket $toolingBucket --s3-prefix code-zip --kms-key-id $toolingKeyArn --output-template-file $toolingTemplate
      - sam package --s3-bucket $tenantBucket --s3-prefix code-zip --kms-key-id $tenantKeyArn --region ap-northeast-1 --output-template-file $tenantTemplate
artifacts:
  discard-paths: true
  files:
    - tooling-package-template.yaml
    - tenant-package-template.yaml